import { TILE_DEFINITIONS, TILE_TYPES } from "./tile.js";

const SWING_WINDOW_SECONDS = 0.18;

function oneSwingPowerFor(tileType) {
  return Math.ceil(TILE_DEFINITIONS[tileType].hp / SWING_WINDOW_SECONDS);
}

function createTool({
  id,
  label,
  materialItemId = null,
  category,
  storeCategory,
  branchId,
  branchLabel,
  price,
  miningPower,
  description,
  oneSwingBlockType = null,
  tier,
  slotCount = null,
  stackSize = null,
  durationSeconds = null,
  isRoot = false,
}) {
  return Object.freeze({
    id,
    label,
    materialItemId,
    category,
    storeCategory,
    branchId,
    branchLabel,
    price,
    miningPower,
    description,
    oneSwingBlockType,
    oneSwingBlockLabel: oneSwingBlockType ? TILE_DEFINITIONS[oneSwingBlockType].label : null,
    tier,
    slotCount,
    stackSize,
    durationSeconds,
    isRoot,
  });
}

export const DEFAULT_GAME_MODE = "standard";
export const DEFAULT_TOOL_ID = "bare-hands";
export const DEFAULT_BAG_ROOT_ID = "trouser-pockets";
export const DEFAULT_CAPACITY_ROOT_ID = "small-size";
export const DEFAULT_TIME_ROOT_ID = "time-root";
export const DEFAULT_SLOT_COUNT = 8;
export const DEFAULT_STACK_SIZE = 8;
export const BAG_SLOT_COUNT = 8;

export const TOOL_DEFINITIONS = Object.freeze({
  [DEFAULT_BAG_ROOT_ID]: createTool({
    id: DEFAULT_BAG_ROOT_ID,
    label: "Trouser Pockets",
    category: "bag-root",
    storeCategory: "storage",
    branchId: "bags",
    branchLabel: "Bag Space",
    price: 0,
    miningPower: 0,
    description: "Your starting carry space, spread across your trouser pockets for 8 total slots.",
    tier: 0,
    slotCount: DEFAULT_SLOT_COUNT,
    isRoot: true,
  }),
  [DEFAULT_CAPACITY_ROOT_ID]: createTool({
    id: DEFAULT_CAPACITY_ROOT_ID,
    label: "Small (8x)",
    category: "capacity-root",
    storeCategory: "storage",
    branchId: "capacity",
    branchLabel: "Pocket Size",
    price: 0,
    miningPower: 0,
    description: "Your starting pocket and bag size: 8 items per slot.",
    tier: 0,
    stackSize: DEFAULT_STACK_SIZE,
    isRoot: true,
  }),
  [DEFAULT_TIME_ROOT_ID]: createTool({
    id: DEFAULT_TIME_ROOT_ID,
    label: "Shift Clock",
    category: "time-root",
    storeCategory: "misc",
    branchId: "time",
    branchLabel: "Time",
    price: 0,
    miningPower: 0,
    description: "Testing default: a short 5-second shift timer.",
    tier: 0,
    durationSeconds: 5,
    isRoot: true,
  }),
  [DEFAULT_TOOL_ID]: createTool({
    id: DEFAULT_TOOL_ID,
    label: "Bare Hands",
    category: "hands",
    storeCategory: "tools",
    branchId: "hands",
    branchLabel: "Pickaxes",
    price: 0,
    miningPower: 38,
    description: "No tool yet. Good enough for scraping out the first few blocks.",
    tier: 0,
  }),
  "wood-pick": createTool({
    id: "wood-pick",
    label: "Wood Pickaxe",
    category: "pickaxe",
    storeCategory: "tools",
    branchId: "pickaxe",
    branchLabel: "Pickaxes",
    price: 12,
    miningPower: 90,
    description: "Your first real pickaxe, mapped to the coal tier of progression.",
    tier: 1,
  }),
  "copper-pick": createTool({
    id: "copper-pick",
    label: "Copper Pickaxe",
    materialItemId: "copper",
    category: "pickaxe",
    storeCategory: "tools",
    branchId: "pickaxe",
    branchLabel: "Pickaxes",
    price: 26,
    miningPower: 130,
    description: "Cuts through the upper vein with a steadier bite.",
    tier: 2,
  }),
  "tin-pick": createTool({
    id: "tin-pick",
    label: "Tin Pickaxe",
    materialItemId: "tin",
    category: "pickaxe",
    storeCategory: "tools",
    branchId: "pickaxe",
    branchLabel: "Pickaxes",
    price: 48,
    miningPower: oneSwingPowerFor(TILE_TYPES.DIRT),
    description: "Strong enough to clear dirt in a single swing.",
    oneSwingBlockType: TILE_TYPES.DIRT,
    tier: 3,
  }),
  "iron-pick": createTool({
    id: "iron-pick",
    label: "Iron Pickaxe",
    materialItemId: "iron",
    category: "pickaxe",
    storeCategory: "tools",
    branchId: "pickaxe",
    branchLabel: "Pickaxes",
    price: 84,
    miningPower: oneSwingPowerFor(TILE_TYPES.STONE),
    description: "Built to crack stone in one swing.",
    oneSwingBlockType: TILE_TYPES.STONE,
    tier: 4,
  }),
  "silver-pick": createTool({
    id: "silver-pick",
    label: "Silver Pickaxe",
    materialItemId: "silver",
    category: "pickaxe",
    storeCategory: "tools",
    branchId: "pickaxe",
    branchLabel: "Pickaxes",
    price: 140,
    miningPower: oneSwingPowerFor(TILE_TYPES.SHALE),
    description: "Turns shale into a one-swing block.",
    oneSwingBlockType: TILE_TYPES.SHALE,
    tier: 5,
  }),
  "gold-pick": createTool({
    id: "gold-pick",
    label: "Gold Pickaxe",
    materialItemId: "gold",
    category: "pickaxe",
    storeCategory: "tools",
    branchId: "pickaxe",
    branchLabel: "Pickaxes",
    price: 220,
    miningPower: oneSwingPowerFor(TILE_TYPES.BASALT),
    description: "Lets you smash basalt in one clean swing.",
    oneSwingBlockType: TILE_TYPES.BASALT,
    tier: 6,
  }),
  "ruby-pick": createTool({
    id: "ruby-pick",
    label: "Ruby Pickaxe",
    materialItemId: "ruby",
    category: "pickaxe",
    storeCategory: "tools",
    branchId: "pickaxe",
    branchLabel: "Pickaxes",
    price: 360,
    miningPower: oneSwingPowerFor(TILE_TYPES.BASALT) + 140,
    description: "A brutal late-game pick for high-yield stone and ore.",
    oneSwingBlockType: TILE_TYPES.BASALT,
    tier: 7,
  }),
  "sapphire-pick": createTool({
    id: "sapphire-pick",
    label: "Sapphire Pickaxe",
    materialItemId: "sapphire",
    category: "pickaxe",
    storeCategory: "tools",
    branchId: "pickaxe",
    branchLabel: "Pickaxes",
    price: 520,
    miningPower: oneSwingPowerFor(TILE_TYPES.BASALT) + 260,
    description: "The top-end pick for tearing through the deepest rock.",
    oneSwingBlockType: TILE_TYPES.BASALT,
    tier: 8,
  }),
  "bag-1": createTool({
    id: "bag-1",
    label: "Backpack",
    category: "bag",
    storeCategory: "storage",
    branchId: "bags",
    branchLabel: "Bag Space",
    price: 18,
    miningPower: 0,
    description: "Adds one extra bag, giving you 8 more slots.",
    tier: 1,
    slotCount: DEFAULT_SLOT_COUNT + BAG_SLOT_COUNT,
  }),
  "bag-2": createTool({
    id: "bag-2",
    label: "Field Satchel",
    category: "bag",
    storeCategory: "storage",
    branchId: "bags",
    branchLabel: "Bag Space",
    price: 54,
    miningPower: 0,
    description: "Adds another bag for a total of 24 slots.",
    tier: 2,
    slotCount: DEFAULT_SLOT_COUNT + BAG_SLOT_COUNT * 2,
  }),
  "bag-3": createTool({
    id: "bag-3",
    label: "Pack Frame",
    category: "bag",
    storeCategory: "storage",
    branchId: "bags",
    branchLabel: "Bag Space",
    price: 162,
    miningPower: 0,
    description: "Adds a third bag for a total of 32 slots.",
    tier: 3,
    slotCount: DEFAULT_SLOT_COUNT + BAG_SLOT_COUNT * 3,
  }),
  "bag-4": createTool({
    id: "bag-4",
    label: "Ore Hauler",
    category: "bag",
    storeCategory: "storage",
    branchId: "bags",
    branchLabel: "Bag Space",
    price: 486,
    miningPower: 0,
    description: "Adds a fourth bag for a total of 40 slots.",
    tier: 4,
    slotCount: DEFAULT_SLOT_COUNT + BAG_SLOT_COUNT * 4,
  }),
  "capacity-1": createTool({
    id: "capacity-1",
    label: "Medium (16x)",
    category: "capacity",
    storeCategory: "storage",
    branchId: "capacity",
    branchLabel: "Pocket Size",
    price: 24,
    miningPower: 0,
    description: "Doubles the size of every slot to hold 16 items each.",
    tier: 1,
    stackSize: DEFAULT_STACK_SIZE * 2,
  }),
  "capacity-2": createTool({
    id: "capacity-2",
    label: "Large (32x)",
    category: "capacity",
    storeCategory: "storage",
    branchId: "capacity",
    branchLabel: "Pocket Size",
    price: 72,
    miningPower: 0,
    description: "Doubles every slot again so each holds 32 items.",
    tier: 2,
    stackSize: DEFAULT_STACK_SIZE * 4,
  }),
  "capacity-3": createTool({
    id: "capacity-3",
    label: "Huge (64x)",
    category: "capacity",
    storeCategory: "storage",
    branchId: "capacity",
    branchLabel: "Pocket Size",
    price: 216,
    miningPower: 0,
    description: "Doubles slot size again so each slot holds 64 items.",
    tier: 3,
    stackSize: DEFAULT_STACK_SIZE * 8,
  }),
  "capacity-4": createTool({
    id: "capacity-4",
    label: "Massive (128x)",
    category: "capacity",
    storeCategory: "storage",
    branchId: "capacity",
    branchLabel: "Pocket Size",
    price: 648,
    miningPower: 0,
    description: "Doubles slot size again so each slot holds 128 items.",
    tier: 4,
    stackSize: DEFAULT_STACK_SIZE * 16,
  }),
  "time-1": createTool({
    id: "time-1",
    label: "Extended Shift",
    category: "time",
    storeCategory: "misc",
    branchId: "time",
    branchLabel: "Time",
    price: 50,
    miningPower: 0,
    description: "Adds another 30 seconds to each round for a total of 90 seconds.",
    tier: 1,
    durationSeconds: 90,
  }),
  "time-2": createTool({
    id: "time-2",
    label: "Deep Shift",
    category: "time",
    storeCategory: "misc",
    branchId: "time",
    branchLabel: "Time",
    price: 500,
    miningPower: 0,
    description: "Pushes the whole round to 150 seconds total.",
    tier: 2,
    durationSeconds: 150,
  }),
});

export const GAME_MODE_DEFINITIONS = Object.freeze({
  [DEFAULT_GAME_MODE]: Object.freeze({
    id: DEFAULT_GAME_MODE,
    label: "Standard Shift",
    toolIds: Object.freeze([
      DEFAULT_BAG_ROOT_ID,
      DEFAULT_CAPACITY_ROOT_ID,
      DEFAULT_TIME_ROOT_ID,
      DEFAULT_TOOL_ID,
      "wood-pick",
      "copper-pick",
      "tin-pick",
      "iron-pick",
      "silver-pick",
      "gold-pick",
      "ruby-pick",
      "sapphire-pick",
      "bag-1",
      "bag-2",
      "bag-3",
      "bag-4",
      "capacity-1",
      "capacity-2",
      "capacity-3",
      "capacity-4",
      "time-1",
      "time-2",
    ]),
  }),
});

export function getToolDefinition(toolId) {
  return TOOL_DEFINITIONS[toolId] ?? TOOL_DEFINITIONS[DEFAULT_TOOL_ID];
}

export function getToolsForGameMode(gameMode = DEFAULT_GAME_MODE) {
  const mode = GAME_MODE_DEFINITIONS[gameMode] ?? GAME_MODE_DEFINITIONS[DEFAULT_GAME_MODE];
  return mode.toolIds.map((toolId) => TOOL_DEFINITIONS[toolId]);
}

export function getToolBranchTools(gameMode = DEFAULT_GAME_MODE, branchId = "pickaxe") {
  return getToolsForGameMode(gameMode).filter((tool) => tool.branchId === branchId);
}
